---
- hosts: all
  gather_facts: false
  tasks:
  - name: Deploy VM windows from template and customize
    vmware_guest:
      hostname: "{{ vc_hostname }}" 
      username: "{{ vc_username }}" 
      password: "{{ vc_password }}" 
      validate_certs: no
      datacenter: "{{ vc_datacenter }}"
      folder: "{{ vc_folder }}"
      cluster: "{{ vc_cluster }}"
      name: "{{ inventory_hostname }}"
      annotation: "{{ vc_note }}"
      state: poweredon
      disk:
      - size_gb: "{{ vm_disksize}}"
        type: thin
        datastore: "{{ vm_datastore }}"
      hardware:
         memory_mb: "{{ vm_memory }}"
         num_cpus: "{{ vm_cpu }}"
         scsi: paravirtual
      template: "{{ vm_template }}" 
      networks:
      - name: "{{ vm_networkportgroup }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_networkmask }}"
        gateway: "{{ vm_networkgw }}"
      customization:
        hostname: "{{ inventory_hostname }}"
        autologon: true
        dns_servers:
        - "{{ vm_networkdns1 }}"
        - "{{ vm_networkdns2 }}"
        dns_suffix: "{{ dc_domain}}" 
        password: "{{ localadminpass }}" 
    delegate_to: localhost
